
use QualityCenter_Demo_db

select* from ORDERFEB2022
SELECT* FROM CUSTOMER

SELECT CUSTOMER.CUSTOMERID, CUSTOMER.CUSTOMERNAME, CUSTOMER.ADDRESS, CUSTOMER.CITY, ORDERFEB2022.ORDERID, ORDERFEB2022.PRODUCTNAME
FROM ORDERFEB2022 LEFT JOIN CUSTOMER
ON CUSTOMER.CUSTOMERID = ORDERFEB2022.CUSTOMERID